package-lock.json
package.json
src/assets/images/icon_download.svg
src/assets/images/icon_upload.svg
src/components/path-choice/choice-slide.tsx
src/components/root.css
src/components/root.js
src/components/shared/header.tsx
src/components/shared/screen-container.tsx
src/components/shared/screen-description.tsx
src/index.js

- Create components for layout
- Fixes CSS for layout and header
- Removes bootstrap

Reskins choice path

---

src/components/download-form/download-form-slide.tsx
src/components/download-started/download-started-slide.tsx

Reskins download screens

---

src/components/payment-invoice/payment-invoice-slide.tsx

Reskins upload stage 2

---

src/components/shared/progress-bar.jsx
src/components/upload-started/upload-started-slide.tsx

Reskins upload stage 3

---

.prettierrc.json
src/components/payment-invoice/index.tsx
src/components/payment-invoice/payment-invoice-slide.tsx
src/components/shared/clipboard-widget.tsx
src/components/upload-progress/index.tsx
src/components/upload-progress/upload-progress-slide.tsx
src/redux/reducers/upload-reducer.tsx

Reskin upload stage 4

---

src/components/payment-invoice/payment-invoice-slide.tsx
src/components/shared/clipboard-widget.tsx
src/components/upload-complete/upload-complete-slide.tsx
src/components/upload-progress/upload-progress-slide.tsx

Reskins upload stage 5

---

src/components/payment-invoice/payment-invoice-slide.tsx
src/components/shared/clipboard-widget.tsx
src/components/upload-form/upload-slide.tsx
src/components/upload-started/upload-started-slide.tsx
src/redux/epics/download-epic.tsx
src/services/error-tracker.tsx

Most of the styling fixes from the bottom of this doc: https://docs.google.com/document/d/1QTnfoGYuvilYWQqG_GcOtFa6yVWjCRK8g8cjgZjNsag/edit#

QA bugs / UX and UI improvements

---

src/components/payment-invoice/payment-invoice-slide.tsx
src/components/shared/clipboard-widget.tsx
src/components/upload-complete/upload-complete-slide.tsx
src/components/upload-progress/upload-progress-slide.tsx
src/config/index.tsx

The button to copy the handle said "Copy Address" so this adds a property property to the clipboard widget so you can specify what you're copying.

Add "property" property to clipboard widget

---

src/components/shared/header.tsx
src/components/shared/screen-container.tsx
src/components/upload-form/upload-slide.tsx
src/components/upload-started/upload-started-slide.tsx
src/config/index.tsx
src/redux/epics/download-epic.tsx
src/services/error-tracker.tsx

Taken from this doc:
https://docs.google.com/document/d/12NXPDbqZrxxAAC4dayx7Y5Kj4YFKmX2U1W7ymPWJnk8/edit

UI / UX improvements

---

src/components/shared/header.tsx
src/components/upload-form/index.tsx
src/components/upload-form/upload-form-slide.tsx

- Still need to create routes / pages for those agreements

Terms and conditions links

---

src/components/shared/header.tsx

Redirecting storage.opacity.io -> opacity.io

Redirect to Opacity.io

---

src/components/download-form/download-form-slide.tsx
src/components/root.css
src/components/upload-form/upload-form-slide.tsx

- Fixes retention slider styles
- Fixes download input width
Desktop
Mobile

Fixes download input width on mobile

---

src/components/register-record-recovery-phrase/index.tsx
src/components/register-record-recovery-phrase/register-record-recovery-phrase-slide.tsx
src/config/index.tsx
src/index.js

Pretty register page

---

package-lock.json
package.json
src/components/register-record-recovery-phrase/index.tsx
src/components/register-record-recovery-phrase/register-record-recovery-phrase-slide.tsx
src/components/root.css
src/components/shared/screen-container.tsx
src/config/index.tsx
src/redux/actions/signup-actions.test.js
src/redux/actions/signup-actions.tsx
src/redux/reducers/index.tsx
src/redux/reducers/signup-reducer.test.js
src/redux/reducers/signup-reducer.tsx

- Fixes CSS
- Mnemonic generator
- Download mnemonic as CSV file
- Redux flow for saving private key

Functionality for record recovery phrase screen

---

src/components/payment-invoice/payment-invoice-slide.tsx
src/components/register-send-payment/register-send-payment-slide.tsx
src/components/shared/metamask-button.js
src/components/shared/outbound-link.tsx
src/components/upload-form/upload-form-slide.tsx
src/config/index.tsx

- Fixes styles
- Refactors shared components (metamask button, outbound link)

Functionality for send payment screen

---

src/components/register-confirm-payment/register-confirm-payment-slide.tsx
src/index.js

- Not sure how/why the route was removed
- Next step: extract all the common components into public ones and use them across all the screens

Fix styles on register confirm payment

---

src/components/root.css
src/components/stands-out/stands-out-slide.tsx
src/index.js

- Fixes path for ToS page
- Fixes white text

Fixes ToS page

---

package-lock.json
package.json

- Latest and greatest
- Allows us to use the new hooks and context API

Upgrades React to v16.8

---

src/components/shared/video-player.tsx
src/components/stands-out/stands-out-slide.tsx
src/components/team-page/team-page-slide.tsx

- Make video bigger
- Fix layout issues on team and stands out pages

Fix layout issues on team and stands out pages

---

.huskyrc.js
package-lock.json
package.json

During commit and push are automatically started unit tests and lint. You can skip all these verifications by add parameter --no-verify

Develpment improvement, upgrade husky, precommit, prepush

---

package-lock.json
package.json
src/components/file-manager/drag-and-drop-overlay.tsx
src/components/file-manager/file-manager-slide.tsx
src/components/file-manager/index.tsx

- Adds drag and drop functionality to the file manager page
- Adds overlay when file is being hovered

Drag and drop functionality

---

d.ts
src/components/agreement/contents.tsx
src/components/agreement/index.tsx
src/components/brokers-down/brokers-down-slide.tsx
src/components/file-manager/file-manager-slide.tsx
src/components/landing-page/index.tsx
src/components/landing-page/landing-page-slide.tsx
src/components/login/login-slide.tsx
src/components/logout/index.tsx
src/components/routes/authenticated-route.tsx
src/components/shared/header.tsx
src/components/shared/screen-container.tsx
src/components/signup/create-account.tsx
src/components/stands-out/index.tsx
src/components/stands-out/stands-out-slide.tsx
src/components/subscription/subscription-slide.tsx
src/components/team-page/index.tsx
src/components/team-page/team-page-slide.tsx
src/config/index.ts
src/index.js
src/redux/actions/authentication-actions.ts
src/redux/reducers/authentication-reducer.ts

- Cleans up header and config
- Cleans up agreement stuff
- Removes header from screen container
- Fixes width for all pages

Sign out link in header and authenticated routes

---

package-lock.json
package.json
src/components/file-manager/file-manager-slide.tsx
src/components/file-manager/index.tsx
src/services/metadata.ts

Fix missing default metadata issue

---

src/components/shared/header.tsx

/login, /sign-up
/file-manager
/, /stands-out, /team-page

Update header links

---

package-lock.json
package.json
src/components/file-manager/file-manager-slide.tsx
src/components/file-manager/index.tsx
src/components/signup/create-account.tsx
src/components/signup/index.tsx
src/components/signup/record-account-handle-slide.tsx
src/config/index.ts
src/redux/actions/authentication-actions.test.js
src/redux/actions/authentication-actions.ts
src/redux/actions/download-actions.test.js
src/redux/actions/files-actions.test.js
src/redux/actions/remove-actions.test.js
src/redux/actions/signup-actions.test.js
src/redux/actions/signup-actions.ts
src/redux/actions/upload-actions.test.js
src/redux/epics/authentication-epic.test.js
src/redux/epics/authentication-epic.ts
src/redux/epics/coinmarketcap-epic.test.js
src/redux/epics/coinmarketcap-epic.ts
src/redux/epics/files-epic.test.js
src/redux/epics/metamask-epic.ts
src/redux/epics/signup-epic.test.js
src/redux/reducers/authentication-reducer.test.js
src/redux/reducers/authentication-reducer.ts
src/redux/reducers/signup-reducer.ts
src/services/backend.ts
src/services/coinmarketcap.ts

- Adds a bunch of tests
- Removes deprecated code
- Upgrades axios to fix vulnerability

Adds tests, fixes Axios vulnerability

---

package-lock.json
package.json
public/index.html
src/components/shared/google-tag-manager.tsx
src/config/index.ts
src/index.js

Adds Google Tag Manager

---

package-lock.json
package.json
src/components/file-manager/file-manager-slide.tsx
src/components/file-manager/index.tsx
src/redux/actions/authentication-actions.ts
src/redux/epics/files-epic.test.js
src/redux/epics/files-epic.ts
src/redux/reducers/authentication-reducer.test.js
src/redux/reducers/authentication-reducer.ts

Account data

---

package-lock.json
package.json
src/components/file-manager/file-manager-slide.tsx
src/components/signup/create-account.tsx
src/config/index.ts
src/helpers.ts

- Updates opaque to 0.2.3
- Adds support for professional plan

Enable professional plan

---

src/components/forgot-page/index.tsx
src/components/login/index.tsx
src/components/login/login-slide.tsx
src/components/team-page/team-page-slide.tsx
src/redux/actions/authentication-actions.test.js
src/redux/actions/authentication-actions.ts
src/redux/epics/authentication-epic.test.js
src/redux/epics/authentication-epic.ts
src/redux/reducers/authentication-reducer.test.js
src/redux/reducers/authentication-reducer.ts

- validation
- api communication

Forgot page

---

.huskyrc.js
package-lock.json
src/components/landing-page/landing-page-slide.tsx

Remove coss

---

public/robots.txt

+ Robots complete
- Waiting for Robots to go live to finish the sitemap.

Added Robots + Sitemap

---

src/components/login/login-slide.tsx

Change forgot link

---

.travis.yml
package-lock.json
package.json
src/assets/images/folder.svg
src/components/file-manager/breadcrumbs.tsx
src/components/file-manager/file-manager-slide.tsx
src/components/file-manager/folder-modal.tsx
src/components/file-manager/index.tsx
src/components/file-manager/upload-mobile-button.tsx
src/components/landing-page/index.tsx
src/components/routes/authenticated-route.tsx
src/index.js
src/redux/actions/folder-actions.test.js
src/redux/actions/folder-actions.ts
src/redux/actions/remove-actions.test.js
src/redux/actions/remove-actions.ts
src/redux/epics/finder-epic.test.js
src/redux/epics/finder-epic.ts
src/redux/epics/folder-epic.test.js
src/redux/epics/folder-epic.ts
src/redux/epics/index.ts
src/redux/epics/remove-epic.test.js
src/redux/epics/remove-epic.ts
src/redux/reducers/finder-reducer.test.js
src/redux/reducers/finder-reducer.ts

- Create folder
- View folder
- Upload to specific folder

View and upload to sub folder
